server:
  port: 8087
spring:
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 127.0.0.1 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    pool: # 连接池最大连接数（使用负值表示没有限制）
      timeout: 0 # 连接超时时间（毫秒）
