management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8001
spring:
  application:
    name: Admin Client
  boot:
    admin:
      client:
        url: 'http://localhost:8000'
